version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - spring-msvc
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - spring-msvc
  msvc-users:
    container_name: msvc-users
    image: users
    ports:
      - "8001:8001"
    env_file: ./msvc-users/.env
    networks:
      - spring-msvc
    depends_on:
      - mysql8
    restart: unless-stopped
  msvc-courses:
    container_name: msvc-courses
    image: courses
    ports:
      - "8002:8002"
    env_file: ./msvc-courses/.env
    networks:
      - spring-msvc
    depends_on:
      - postgres14
      - msvc-users
    restart: unless-stopped

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring-msvc:
    name: spring-msvc